version: '3.8'
services:
  localstack:
    image: localstack/localstack:latest
    container_name: sgoodie-localstack
    environment:
      SERVICES: s3,dynamodb
      DEBUG: 1
    ports:
      - "4566:4566"
    volumes:
      - localstack_data:/var/lib/localstack
    tmpfs:
      - /tmp

volumes:
  localstack_data:
